name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  my_new_project:
    +schema: raw
    +quote_columns: true
